import { PrismaClient, Role } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

async function main() {
  console.log("🌱 Starting seed...");

  // Categories
  const [dogs, cats, food, toys, accessories, birds] = await Promise.all([
    prisma.category.upsert({
      where: { name: "สุนัข" },
      update: {},
      create: { name: "สุนัข", slug: "dogs" },
    }),
    prisma.category.upsert({
      where: { name: "แมว" },
      update: {},
      create: { name: "แมว", slug: "cats" },
    }),
    prisma.category.upsert({
      where: { name: "อาหาร" },
      update: {},
      create: { name: "อาหาร", slug: "food" },
    }),
    prisma.category.upsert({
      where: { name: "ของเล่น" },
      update: {},
      create: { name: "ของเล่น", slug: "toys" },
    }),
    prisma.category.upsert({
      where: { name: "อุปกรณ์" },
      update: {},
      create: { name: "อุปกรณ์", slug: "accessories" },
    }),
    prisma.category.upsert({
      where: { name: "นก" },
      update: {},
      create: { name: "นก", slug: "birds" },
    }),
  ]);

  console.log("✅ Categories created");

  // Admin user
  const hashedPassword = await bcrypt.hash("admin1234", 10);
  await prisma.user.upsert({
    where: { email: "admin@petshop.com" },
    update: {},
    create: {
      email: "admin@petshop.com",
      password: hashedPassword,
      name: "Admin",
      phone: "0812345678",
      address: "123 Admin St",
      role: Role.ADMIN,
    },
  });

  console.log("✅ Admin user created");

  // Products
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const products: any[] = [
    // สุนัข (10)
    {
      name: "สายจูงหนังแท้ พรีเมียม",
      description: "สายจูงหนังแท้คุณภาพสูง นุ่มมือ ทนทาน เหมาะสำหรับสุนัขทุกสายพันธุ์",
      price: 590,
      stock: 50,
      categoryId: dogs.id,
      petType: "DOG",
      featured: true,
      images: ["https://placehold.co/600x400?text=Dog+Leash"],
    },
    {
      name: "ปลอกคอสุนัข LED กันน้ำ",
      description: "ปลอกคอ LED มองเห็นได้ในที่มืด ปรับขนาดได้ กันน้ำ เหมาะสำหรับเดินกลางคืน",
      price: 350,
      stock: 80,
      categoryId: dogs.id,
      petType: "DOG",
      featured: false,
      images: ["https://placehold.co/600x400?text=Dog+Collar+LED"],
    },
    {
      name: "เสื้อผ้าสุนัข ลายตาราง",
      description: "เสื้อผ้าสุนัขผ้าฝ้าย 100% ลายตารางน่ารัก ระบายอากาศดี มีหลายไซส์",
      price: 280,
      stock: 60,
      categoryId: dogs.id,
      petType: "DOG",
      featured: false,
      images: ["https://placehold.co/600x400?text=Dog+Clothes"],
    },
    {
      name: "บ้านสุนัข ไม้สน รุ่น Classic",
      description: "บ้านสุนัขทำจากไม้สนธรรมชาติ กันฝน ทนทาน มีช่องระบายอากาศ",
      price: 1890,
      stock: 20,
      categoryId: dogs.id,
      petType: "DOG",
      featured: true,
      images: ["https://placehold.co/600x400?text=Dog+House"],
    },
    {
      name: "แชมพูสุนัข สูตรอ่อนโยน",
      description: "แชมพูสูตรพิเศษสำหรับสุนัข ไม่ระคายเคืองผิว หอมสะอาด ขนาด 500ml",
      price: 220,
      stock: 100,
      categoryId: dogs.id,
      petType: "DOG",
      featured: false,
      images: ["https://placehold.co/600x400?text=Dog+Shampoo"],
    },
    {
      name: "ที่นอนสุนัข Memory Foam",
      description: "ที่นอนโฟมพิเศษรองรับน้ำหนักได้ดี ผ้าคลุมซักได้ เหมาะสำหรับสุนัขสูงอายุ",
      price: 1290,
      stock: 35,
      categoryId: dogs.id,
      petType: "DOG",
      featured: true,
      images: ["https://placehold.co/600x400?text=Dog+Bed"],
    },
    {
      name: "กรงสุนัข พับได้ สแตนเลส",
      description: "กรงสุนัขสแตนเลสพับเก็บได้ ง่ายต่อการพกพา มีถาดรองด้านล่าง",
      price: 2490,
      stock: 15,
      categoryId: dogs.id,
      petType: "DOG",
      featured: false,
      images: ["https://placehold.co/600x400?text=Dog+Crate"],
    },
    {
      name: "ชามอาหารสุนัข สแตนเลส 2 ใบ",
      description: "ชามสแตนเลสคุณภาพสูง พร้อมฐานยางกันลื่น บรรจุน้ำและอาหารได้ในชุดเดียว",
      price: 390,
      stock: 70,
      categoryId: dogs.id,
      petType: "DOG",
      featured: false,
      images: ["https://placehold.co/600x400?text=Dog+Bowl"],
    },
    {
      name: "แปรงหวีขนสุนัข Self-Cleaning",
      description: "แปรงหวีขนระบบ self-cleaning กดปุ่มเดียวดึงขนออก เหมาะกับสุนัขขนยาว",
      price: 450,
      stock: 55,
      categoryId: dogs.id,
      petType: "DOG",
      featured: false,
      images: ["https://placehold.co/600x400?text=Dog+Brush"],
    },
    {
      name: "รองเท้าสุนัข กันลื่น 4 ชิ้น",
      description: "รองเท้าสุนัขกันลื่น กันร้อน ทำจากยางนุ่ม มัดแน่นไม่หลุด",
      price: 320,
      stock: 40,
      categoryId: dogs.id,
      petType: "DOG",
      featured: false,
      images: ["https://placehold.co/600x400?text=Dog+Shoes"],
    },
    // แมว (10)
    {
      name: "บ้านแมว คอนโด 3 ชั้น",
      description: "คอนโดแมว 3 ชั้น มีกระบะทรายและที่ลับเล็บ พร้อมของเล่นห้อย",
      price: 2190,
      stock: 25,
      categoryId: cats.id,
      petType: "CAT",
      featured: true,
      images: ["https://placehold.co/600x400?text=Cat+Condo"],
    },
    {
      name: "ที่ลับเล็บแมว ลำต้นไม้",
      description: "ที่ลับเล็บทำจากไม้ธรรมชาติ ห่อด้วยเชือกป่าน ทนทาน ไม่เป็นเศษ",
      price: 590,
      stock: 45,
      categoryId: cats.id,
      petType: "CAT",
      featured: false,
      images: ["https://placehold.co/600x400?text=Cat+Scratcher"],
    },
    {
      name: "กระบะทรายแมว มีฝาปิด",
      description: "กระบะทรายระบบปิด ลดกลิ่น กันทรายกระจาย มีตัวกรองกลิ่น",
      price: 890,
      stock: 30,
      categoryId: cats.id,
      petType: "CAT",
      featured: true,
      images: ["https://placehold.co/600x400?text=Cat+Litter+Box"],
    },
    {
      name: "ปลอกคอแมว พร้อมกระดิ่ง",
      description: "ปลอกคอแมวผ้าไนลอน มีกระดิ่งน่ารัก ปรับขนาดได้ ระบบ safety release",
      price: 180,
      stock: 90,
      categoryId: cats.id,
      petType: "CAT",
      featured: false,
      images: ["https://placehold.co/600x400?text=Cat+Collar"],
    },
    {
      name: "แชมพูแมว สูตร Hypoallergenic",
      description: "แชมพูแมวสูตรพิเศษสำหรับผิวแพ้ง่าย ปลอดสารเคมีอันตราย ขนาด 300ml",
      price: 260,
      stock: 75,
      categoryId: cats.id,
      petType: "CAT",
      featured: false,
      images: ["https://placehold.co/600x400?text=Cat+Shampoo"],
    },
    {
      name: "ที่นอนแมว รูปถ้วย Fluffy",
      description: "ที่นอนแมวรูปถ้วยขนฟู นุ่มสบาย อบอุ่น ซักได้ มีหลายสี",
      price: 690,
      stock: 50,
      categoryId: cats.id,
      petType: "CAT",
      featured: true,
      images: ["https://placehold.co/600x400?text=Cat+Bed"],
    },
    {
      name: "กระเป๋าเดินทางแมว Airline Approved",
      description: "กระเป๋าสำหรับพาแมวเดินทาง ผ่านมาตรฐานสายการบิน ระบายอากาศดี",
      price: 1490,
      stock: 20,
      categoryId: cats.id,
      petType: "CAT",
      featured: false,
      images: ["https://placehold.co/600x400?text=Cat+Carrier"],
    },
    {
      name: "น้ำหอมแมว กลิ่น Lavender",
      description: "น้ำหอมแมวกลิ่น lavender ไล่กลิ่น ทำจากส่วนผสมธรรมชาติ ขนาด 150ml",
      price: 290,
      stock: 60,
      categoryId: cats.id,
      petType: "CAT",
      featured: false,
      images: ["https://placehold.co/600x400?text=Cat+Perfume"],
    },
    {
      name: "สายจูงแมว + เสื้อกั๊ก",
      description: "สายจูงแมวพร้อมเสื้อกั๊กนิรภัย ไม่รัดคอ เหมาะสำหรับพาแมวออกนอกบ้าน",
      price: 420,
      stock: 35,
      categoryId: cats.id,
      petType: "CAT",
      featured: false,
      images: ["https://placehold.co/600x400?text=Cat+Harness"],
    },
    {
      name: "น้ำพุแมว กรองน้ำ อัตโนมัติ",
      description: "น้ำพุสำหรับแมว กรองน้ำ 3 ชั้น เงียบ กำลังไฟต่ำ ความจุ 2 ลิตร",
      price: 890,
      stock: 40,
      categoryId: cats.id,
      petType: "CAT",
      featured: true,
      images: ["https://placehold.co/600x400?text=Cat+Fountain"],
    },
    // อาหาร (10)
    {
      name: "อาหารสุนัข Royal Canin Adult 10kg",
      description: "อาหารเม็ดสุนัขโต Royal Canin สูตรสมดุล บำรุงขน ระบบย่อยดี ขนาด 10kg",
      price: 1890,
      stock: 40,
      categoryId: food.id,
      petType: "DOG",
      featured: true,
      images: ["https://placehold.co/600x400?text=Dog+Food+Royal+Canin"],
    },
    {
      name: "อาหารแมว Whiskas ปลาทู 1.2kg",
      description: "อาหารเม็ดแมว Whiskas รสปลาทู บำรุงขนและผิวหนัง มีใยอาหาร ขนาด 1.2kg",
      price: 280,
      stock: 100,
      categoryId: food.id,
      petType: "CAT",
      featured: false,
      images: ["https://placehold.co/600x400?text=Cat+Food+Whiskas"],
    },
    {
      name: "อาหารเปียกสุนัข Pedigree รสเนื้อ 12 ซอง",
      description: "อาหารเปียกสุนัข Pedigree รสเนื้อวัว อุดมด้วยโปรตีน แพ็ค 12 ซอง",
      price: 360,
      stock: 80,
      categoryId: food.id,
      petType: "DOG",
      featured: false,
      images: ["https://placehold.co/600x400?text=Dog+Wet+Food"],
    },
    {
      name: "ขนมสุนัข Milk Bone กระดูก",
      description: "ขนมสุนัขรูปกระดูก เสริมแคลเซียม บำรุงฟัน ไม่มีสารกันบูด",
      price: 199,
      stock: 120,
      categoryId: food.id,
      petType: "DOG",
      featured: false,
      images: ["https://placehold.co/600x400?text=Dog+Treat"],
    },
    {
      name: "อาหารนกแก้ว ผสมเมล็ดธัญพืช 1kg",
      description: "อาหารนกแก้วสูตรพิเศษ ผสมเมล็ดธัญพืช ดอกไม้แห้ง อุดมด้วยวิตามิน",
      price: 350,
      stock: 60,
      categoryId: food.id,
      petType: "BIRD",
      featured: false,
      images: ["https://placehold.co/600x400?text=Bird+Food"],
    },
    {
      name: "อาหารแมว Pro Plan Sterilised 3kg",
      description: "อาหารแมวทำหมัน Pro Plan สูตรควบคุมน้ำหนัก บำรุงไต ขนาด 3kg",
      price: 990,
      stock: 45,
      categoryId: food.id,
      petType: "CAT",
      featured: true,
      images: ["https://placehold.co/600x400?text=Cat+Food+Pro+Plan"],
    },
    {
      name: "ขนมแมว Temptations รสไก่",
      description: "ขนมแมว Temptations รสไก่ กรุบนอก นุ่มใน อร่อยถูกใจแมว ขนาด 180g",
      price: 160,
      stock: 150,
      categoryId: food.id,
      petType: "CAT",
      featured: false,
      images: ["https://placehold.co/600x400?text=Cat+Treat"],
    },
    {
      name: "อาหารปลาทอง เม็ดลอยน้ำ 200g",
      description: "อาหารปลาทองสูตรพิเศษ เม็ดลอยน้ำ เสริมสีสัน บำรุงครีบ ขนาด 200g",
      price: 120,
      stock: 200,
      categoryId: food.id,
      petType: "FISH",
      featured: false,
      images: ["https://placehold.co/600x400?text=Fish+Food"],
    },
    {
      name: "อาหารกระต่าย Timothy Hay 500g",
      description: "หญ้า Timothy คุณภาพสูง สำหรับกระต่าย อุดมด้วยไฟเบอร์ ช่วยย่อยอาหาร",
      price: 250,
      stock: 70,
      categoryId: food.id,
      petType: "RABBIT",
      featured: false,
      images: ["https://placehold.co/600x400?text=Rabbit+Food"],
    },
    {
      name: "วิตามินรวมสุนัข Beaphar Multivitamin",
      description: "วิตามินรวมสุนัข เสริมภูมิคุ้มกัน บำรุงขนและกระดูก แบบเม็ด 150 เม็ด",
      price: 490,
      stock: 55,
      categoryId: food.id,
      petType: "DOG",
      featured: false,
      images: ["https://placehold.co/600x400?text=Dog+Vitamins"],
    },
    // ของเล่น (10)
    {
      name: "ลูกบอลเด้งสุนัข Kong Classic",
      description: "ลูกบอลยาง Kong ทนทาน ใส่ขนมได้ กระตุ้นสัญชาตญาณ เหมาะสำหรับสุนัขชอบเคี้ยว",
      price: 390,
      stock: 60,
      categoryId: toys.id,
      petType: "DOG",
      featured: true,
      images: ["https://placehold.co/600x400?text=Kong+Ball"],
    },
    {
      name: "ไม้ตกแมว ขนนก",
      description: "ไม้ตกแมวขนนกแท้ ด้ามยาว 60cm เคลื่อนไหวน่าสนใจ กระตุ้นให้แมวออกกำลัง",
      price: 150,
      stock: 100,
      categoryId: toys.id,
      petType: "CAT",
      featured: false,
      images: ["https://placehold.co/600x400?text=Cat+Feather+Wand"],
    },
    {
      name: "ของเล่นสุนัข เชือกถัก",
      description: "ของเล่นเชือกถักฝ้าย 3 ปม ทนทาน เหมาะสำหรับเล่นดึงกัน ทำความสะอาดง่าย",
      price: 180,
      stock: 80,
      categoryId: toys.id,
      petType: "DOG",
      featured: false,
      images: ["https://placehold.co/600x400?text=Dog+Rope+Toy"],
    },
    {
      name: "ลูกบอลไฟฟ้าแมว หมุนอัตโนมัติ",
      description: "ลูกบอลไฟฟ้าสำหรับแมว หมุนเองอัตโนมัติ หยุดเมื่อถูกจับ ชาร์จ USB ได้",
      price: 590,
      stock: 45,
      categoryId: toys.id,
      petType: "CAT",
      featured: true,
      images: ["https://placehold.co/600x400?text=Cat+Electric+Ball"],
    },
    {
      name: "ของเล่นนกแก้ว บล็อกไม้สี",
      description: "ของเล่นนกแก้วบล็อกไม้สีสัน กัดเล่นได้ ฝึกทักษะสมอง ปลอดสารพิษ",
      price: 220,
      stock: 50,
      categoryId: toys.id,
      petType: "BIRD",
      featured: false,
      images: ["https://placehold.co/600x400?text=Bird+Toy"],
    },
    {
      name: "กระดานฝึกสมองสุนัข Puzzle",
      description: "กระดานปริศนาสำหรับสุนัข ซ่อนขนมแล้วให้หา ระดับปรับได้ พัฒนา IQ",
      price: 850,
      stock: 30,
      categoryId: toys.id,
      petType: "DOG",
      featured: false,
      images: ["https://placehold.co/600x400?text=Dog+Puzzle"],
    },
    {
      name: "หนูยางแมวบรรจุ Catnip",
      description: "ตุ๊กตาหนูยางบรรจุ catnip กระตุ้นให้แมวเล่น มีเสียงกริ๊งเมื่อกัด",
      price: 120,
      stock: 120,
      categoryId: toys.id,
      petType: "CAT",
      featured: false,
      images: ["https://placehold.co/600x400?text=Catnip+Mouse"],
    },
    {
      name: "ลูกบอลสุนัข มีเสียงดัง",
      description: "ลูกบอลยางมีเสียงดัง กระตุ้นสัญชาตญาณ สีสันสดใส ขนาด 7cm",
      price: 99,
      stock: 150,
      categoryId: toys.id,
      petType: "DOG",
      featured: false,
      images: ["https://placehold.co/600x400?text=Squeaky+Ball"],
    },
    {
      name: "แผ่นขุดหาอาหารสุนัข Snuffle Mat",
      description: "แผ่นหญ้าเทียมซ่อนอาหาร ฝึกการดมกลิ่น ลดความเครียด ซักเครื่องได้",
      price: 650,
      stock: 35,
      categoryId: toys.id,
      petType: "DOG",
      featured: true,
      images: ["https://placehold.co/600x400?text=Snuffle+Mat"],
    },
    {
      name: "อุโมงค์แมว พับได้",
      description: "อุโมงค์แมวผ้า Oxford พับเก็บได้ มีรูข้าง 3 จุด มีลูกบอลห้อย",
      price: 380,
      stock: 40,
      categoryId: toys.id,
      petType: "CAT",
      featured: false,
      images: ["https://placehold.co/600x400?text=Cat+Tunnel"],
    },
    // อุปกรณ์ (10)
    {
      name: "เครื่องให้อาหารอัตโนมัติ Wi-Fi",
      description: "เครื่องให้อาหารสัตว์เลี้ยงอัตโนมัติ ควบคุมผ่าน App มีกล้อง ความจุ 4 ลิตร",
      price: 2890,
      stock: 15,
      categoryId: accessories.id,
      petType: null,
      featured: true,
      images: ["https://placehold.co/600x400?text=Auto+Feeder"],
    },
    {
      name: "GPS Tracker สำหรับสัตว์เลี้ยง",
      description: "GPS ติดตามสัตว์เลี้ยงแบบ real-time กันน้ำ แบตฯ อยู่ได้ 7 วัน",
      price: 1990,
      stock: 25,
      categoryId: accessories.id,
      petType: null,
      featured: true,
      images: ["https://placehold.co/600x400?text=GPS+Tracker"],
    },
    {
      name: "ไดร์เป่าขนสุนัข 2200W",
      description: "ไดร์เป่าขนสุนัขกำลังสูง 2200W ปรับลมและอุณหภูมิได้ เงียบ",
      price: 1490,
      stock: 20,
      categoryId: accessories.id,
      petType: "DOG",
      featured: false,
      images: ["https://placehold.co/600x400?text=Dog+Dryer"],
    },
    {
      name: "ตาชั่งดิจิทัล สัตว์เลี้ยง",
      description: "ตาชั่งดิจิทัลสำหรับสัตว์เลี้ยง ชั่งได้ถึง 50kg หน้าจอ LCD ชัดเจน",
      price: 790,
      stock: 30,
      categoryId: accessories.id,
      petType: null,
      featured: false,
      images: ["https://placehold.co/600x400?text=Pet+Scale"],
    },
    {
      name: "ที่ตัดเล็บสัตว์เลี้ยง Guillotine",
      description: "กรรไกรตัดเล็บระบบ guillotine คมตลอด กันบาด เหมาะสำหรับสุนัขและแมว",
      price: 290,
      stock: 70,
      categoryId: accessories.id,
      petType: null,
      featured: false,
      images: ["https://placehold.co/600x400?text=Nail+Clipper"],
    },
    {
      name: "กรงนกแก้ว สแตนเลส ขนาดใหญ่",
      description: "กรงนกแก้วสแตนเลสคุณภาพสูง ขนาด 60x50x120cm มีชั้นวางและรางอาหาร",
      price: 3490,
      stock: 10,
      categoryId: accessories.id,
      petType: "BIRD",
      featured: false,
      images: ["https://placehold.co/600x400?text=Bird+Cage"],
    },
    {
      name: "ตู้ปลา SET พร้อมใช้ 60cm",
      description: "ตู้ปลาแก้ว 60cm พร้อมกรอง ปั๊มลม ไฟ LED และกรวดสี ครบชุด",
      price: 2290,
      stock: 12,
      categoryId: accessories.id,
      petType: "FISH",
      featured: true,
      images: ["https://placehold.co/600x400?text=Fish+Tank"],
    },
    {
      name: "แปรงสีฟันสุนัข พร้อมยาสีฟัน",
      description: "แปรงสีฟันสุนัข 3 หัว พร้อมยาสีฟันรสไก่ ป้องกันหินปูน กลิ่นปาก",
      price: 250,
      stock: 85,
      categoryId: accessories.id,
      petType: "DOG",
      featured: false,
      images: ["https://placehold.co/600x400?text=Dog+Toothbrush"],
    },
    {
      name: "เสื่อกันน้ำ สำหรับรถยนต์",
      description: "เสื่อกันน้ำสำหรับวางสัตว์เลี้ยงในรถ กันขน กันเลอะ ซักได้ ขนาด 140x150cm",
      price: 690,
      stock: 40,
      categoryId: accessories.id,
      petType: null,
      featured: false,
      images: ["https://placehold.co/600x400?text=Car+Seat+Cover"],
    },
    {
      name: "กระเป๋าเป้สะพายหลัง ใส่สัตว์เลี้ยง",
      description: "กระเป๋าเป้ใส่สัตว์เลี้ยง มีหน้าต่างใส ระบายอากาศดี รับน้ำหนักได้ 8kg",
      price: 1290,
      stock: 22,
      categoryId: accessories.id,
      petType: null,
      featured: false,
      images: ["https://placehold.co/600x400?text=Pet+Backpack"],
    },
  ];

  for (const product of products) {
    await prisma.product.create({ data: product });
  }

  console.log(`✅ ${products.length} products created`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
